### ISSUE TITLE
Provide a benchmark suitable for showing JRuby slowness

### ISSUE THREAD

**Issue by headius** [astroband/ruby-stellar-base#47]
I was pointed to your readme today since it mentions that JRuby is slow due to BigDecimal performance, but I did not see any benchmarks or other means of exercising that behavior. If you can provide a benchmark that shows the JRuby performance issues, we might be able to do something to improve it.

Alternatively, we consider sub-par performance to be an issue, so if someone could file an issue at jruby/jruby with a reproducible benchmark, we'll have a look!

**Comment by ramontayag** [comment]
Hey @headius. Yes, that's right it says that on the readme. It was written a while back, and Bloom has since become the maintainer of the repo. I'm not hopeful that we'll find out what the slowness is/was. When we do see it or if someone reports it, I'll circle back here.

Thanks for reaching out -- your dedication to JRuby is amazing!
